import { typeCarDetail } from "@/types";

export enum CarTypes {
  suv = "SUV",
  ute = "Ute",
  hatch = "Hatch",
  sedan = "Sedan",
  van = "Van",
  coupe = "Coupe",
  wagon = "Wagon",
  peopleMover = "People_Mover",
}

export type CarTypeData = {
  [key in CarTypes]: typeCarDetail[];
};

export const TYPE_FILTER_TABS: CarTypes[] = [
  CarTypes.suv,
  CarTypes.hatch,
  CarTypes.sedan,
  CarTypes.van,
  CarTypes.coupe,
  CarTypes.wagon,
  CarTypes.peopleMover,
];

export const CAR_TYPE_DATA: CarTypeData = {
  SUV: [
    {
      imageUrl: "/carTypeImage/hyundai-creta.png",
      year: 2022,
      make: "Hyundai",
      model: "Creta",
      variant: "SX (O)",
      mileage: 35000,
      transmission: "Automatic",
      price: 4850000,
    },
    {
      imageUrl: "/carTypeImage/mahindra-xuv700.png",
      year: 2023,
      make: "Mahindra",
      model: "Scorpio-N",
      variant: "Z8 L 4WD",
      mileage: 18500,
      transmission: "Automatic",
      price: 11500000,
    },
    {
      imageUrl: "/carTypeImage/suzuki-brezza.png",
      year: 2023,
      make: "Suzuki",
      model: "Brezza",
      variant: "ZXi+ AT",
      mileage: 15200,
      transmission: "Automatic",
      price: 4400000,
    },
    {
      imageUrl: "/carTypeImage/tata-nexon-ev.png",
      year: 2022,
      make: "Tata",
      model: "Nexon EV",
      variant: "XZ+ Lux (Prime)",
      mileage: 29800,
      transmission: "Automatic",
      price: 3750000,
    },
    {
      imageUrl: "/carTypeImage/ford-endeavour.png",
      year: 2020,
      make: "Ford",
      model: "Endeavour",
      variant: "Titanium+ 4x4",
      mileage: 62500,
      transmission: "Automatic",
      price: 9500000,
    },
    {
      imageUrl: "/carTypeImage/hyundai-creta.png",
      year: 2022,
      make: "Hyundai",
      model: "Creta",
      variant: "SX (O)",
      mileage: 35000,
      transmission: "Automatic",
      price: 4850000,
    },
    {
      imageUrl: "/carTypeImage/mahindra-xuv700.png",
      year: 2023,
      make: "Mahindra",
      model: "Scorpio-N",
      variant: "Z8 L 4WD",
      mileage: 18500,
      transmission: "Automatic",
      price: 11500000,
    },
    {
      imageUrl: "/carTypeImage/suzuki-brezza.png",
      year: 2023,
      make: "Suzuki",
      model: "Brezza",
      variant: "ZXi+ AT",
      mileage: 15200,
      transmission: "Automatic",
      price: 4400000,
    },
    {
      imageUrl: "/carTypeImage/tata-nexon-ev.png",
      year: 2022,
      make: "Tata",
      model: "Nexon EV",
      variant: "XZ+ Lux (Prime)",
      mileage: 29800,
      transmission: "Automatic",
      price: 3750000,
    },
  ],
  // Ute: [
  //   {
  //     imageUrl: "/cars/toyota-hilux-ute.png",
  //     year: 2021,
  //     make: "Toyota",
  //     model: "Hilux",
  //     variant: "SR5 (4x4)",
  //     mileage: 75200,
  //     transmission: "Automatic",
  //     price: 55990,
  //   },
  //   {
  //     imageUrl: "/cars/ford-ranger-ute.png",
  //     year: 2022,
  //     make: "Ford",
  //     model: "Ranger",
  //     variant: "Wildtrak 3.0 (4x4)",
  //     mileage: 42800,
  //     transmission: "Automatic",
  //     price: 69990,
  //   },
  //   {
  //     imageUrl: "/cars/isuzu-dmax-ute.png",
  //     year: 2021,
  //     make: "Isuzu",
  //     model: "D-MAX",
  //     variant: "X-TERRAIN (4x4)",
  //     mileage: 65150,
  //     transmission: "Automatic",
  //     price: 58990,
  //   },
  //   {
  //     imageUrl: "/cars/mitsubishi-triton-ute.png",
  //     year: 2020,
  //     make: "Mitsubishi",
  //     model: "Triton",
  //     variant: "GLS Premium (4x4)",
  //     mileage: 88000,
  //     transmission: "Automatic",
  //     price: 45000,
  //   },
  // ],
  Hatch: [
    {
      imageUrl: "/carTypeImage/vw-golf-hatch.png",
      year: 2020,
      make: "Volkswagen",
      model: "Golf",
      variant: "GTI",
      mileage: 42345,
      transmission: "Automatic",
      price: 38500,
    },
    {
      imageUrl: "/carTypeImage/hyundai-i30-hatch.png",
      year: 2022,
      make: "Hyundai",
      model: "i30",
      variant: "N Line",
      mileage: 19500,
      transmission: "Automatic",
      price: 31500,
    },
    {
      imageUrl: "/carTypeImage/subaru-impreza-hatch.png",
      year: 2021,
      make: "Subaru",
      model: "Impreza",
      variant: "2.0i-S (AWD)",
      mileage: 41000,
      transmission: "Automatic",
      price: 28990,
    },
    {
      imageUrl: "/carTypeImage/mazda-cx30-hatch.png",
      year: 2021,
      make: "Mazda",
      model: "CX-30",
      variant: "G20 Evolve (FWD)",
      mileage: 54127,
      transmission: "Automatic",
      price: 26990,
    },
  ],
  Sedan: [
    {
      imageUrl: "/carTypeImage/mazda-3-sedan.png",
      year: 2023,
      make: "Mazda",
      model: "3",
      variant: "G25 Astina",
      mileage: 15549,
      transmission: "Automatic",
      price: 46990,
    },
    {
      imageUrl: "/carTypeImage/toyota-camry-sedan.png",
      year: 2021,
      make: "Toyota",
      model: "Camry",
      variant: "Ascent Hybrid",
      mileage: 68300,
      transmission: "Automatic",
      price: 35990,
    },
    {
      imageUrl: "/carTypeImage/honda-accord-sedan.png",
      year: 2022,
      make: "Honda",
      model: "Accord",
      variant: "VTi-LX Hybrid",
      mileage: 25500,
      transmission: "Automatic",
      price: 46500,
    },
    {
      imageUrl: "/carTypeImage/mercedes-c300-sedan.png",
      year: 2020,
      make: "Mercedes-Benz",
      model: "C-Class",
      variant: "C300",
      mileage: 45100,
      transmission: "Automatic",
      price: 62000,
    },
  ],
  Van: [
    {
      imageUrl: "/carTypeImage/ford-transit-van.png",
      year: 2019,
      make: "Ford",
      model: "Transit Custom",
      variant: "320S (SWB)",
      mileage: 110540,
      transmission: "Automatic",
      price: 34990,
    },
    {
      imageUrl: "/carTypeImage/toyota-hiace-van.png",
      year: 2022,
      make: "Toyota",
      model: "HiAce",
      variant: "LWB",
      mileage: 31000,
      transmission: "Automatic",
      price: 47990,
    },
    {
      imageUrl: "/carTypeImage/vw-transporter-van.png",
      year: 2021,
      make: "Volkswagen",
      model: "Transporter",
      variant: "TDI340 SWB",
      mileage: 72500,
      transmission: "Automatic",
      price: 42500,
    },
    {
      imageUrl: "/carTypeImage/renault-kangoo-van.png",
      year: 2019,
      make: "Renault",
      model: "Kangoo",
      variant: "Maxi",
      mileage: 105200,
      transmission: "Automatic",
      price: 21990,
    },
  ],
  Coupe: [
    {
      imageUrl: "/carTypeImage/ford-mustang-coupe.png",
      year: 2021,
      make: "Ford",
      model: "Mustang",
      variant: "GT 5.0L V8",
      mileage: 18000,
      transmission: "Automatic",
      price: 68990,
    },
    {
      imageUrl: "/carTypeImage/nissan-z-coupe.png",
      year: 2023,
      make: "Nissan",
      model: "Z",
      variant: "Proto Spec",
      mileage: 5500,
      transmission: "Automatic",
      price: 85000,
    },
    {
      imageUrl: "/carTypeImage/bmw-m2-coupe.png",
      year: 2020,
      make: "BMW",
      model: "M2",
      variant: "Competition",
      mileage: 29000,
      transmission: "Automatic",
      price: 92500,
    },
    {
      imageUrl: "/carTypeImage/subaru-brz-coupe.png",
      year: 2022,
      make: "Subaru",
      model: "BRZ",
      variant: "S Coupe",
      mileage: 12100,
      transmission: "Manual",
      price: 41990,
    },
  ],
  Wagon: [
    {
      imageUrl: "/carTypeImage/audi-a4-wagon.png",
      year: 2020,
      make: "Audi",
      model: "A4 Avant",
      variant: "45 TFSI quattro S line",
      mileage: 61000,
      transmission: "Automatic",
      price: 52990,
    },
    {
      imageUrl: "/carTypeImage/subaru-outback-wagon.png",
      year: 2022,
      make: "Subaru",
      model: "Outback",
      variant: "Touring XT (AWD)",
      mileage: 28000,
      transmission: "Automatic",
      price: 51000,
    },
    {
      imageUrl: "/carTypeImage/vw-passat-wagon.png",
      year: 2021,
      make: "Volkswagen",
      model: "Passat Alltrack",
      variant: "162TSI Premium",
      mileage: 55400,
      transmission: "Automatic",
      price: 47990,
    },
    {
      imageUrl: "/carTypeImage/volvo-v60-wagon.png",
      year: 2020,
      make: "Volvo",
      model: "V60",
      variant: "T5 Momentum",
      mileage: 64120,
      transmission: "Automatic",
      price: 44500,
    },
  ],
  People_Mover: [
    {
      imageUrl: "/carTypeImage/kia-carnival-mover.png",
      year: 2022,
      make: "Kia",
      model: "Carnival",
      variant: "Platinum",
      mileage: 35000,
      transmission: "Automatic",
      price: 61990,
    },
    {
      imageUrl: "/carTypeImage/hyundai-staria-mover.png",
      year: 2022,
      make: "Hyundai",
      model: "Staria",
      variant: "Highlander",
      mileage: 22500,
      transmission: "Automatic",
      price: 62500,
    },
    {
      imageUrl: "/carTypeImage/honda-odyssey-mover.png",
      year: 2021,
      make: "Honda",
      model: "Odyssey",
      variant: "Vi LX7",
      mileage: 48000,
      transmission: "Automatic",
      price: 45990,
    },
    {
      imageUrl: "/carTypeImage/mercedes-vclass-mover.png",
      year: 2019,
      make: "Mercedes-Benz",
      model: "V-Class",
      variant: "V250d Avantgarde",
      mileage: 89300,
      transmission: "Automatic",
      price: 88000,
    },
  ],
  [CarTypes.ute]: []
};

const allTypeCars: typeCarDetail[] = Object.values(CAR_TYPE_DATA).flat();

export const CAR_TYPE_IMAGE_BY_MAKE_MODEL: Record<string, string> =
  allTypeCars.reduce<Record<string, string>>((acc, car) => {
    const key = `${car.make}|${car.model}`;
    if (!acc[key]) acc[key] = car.imageUrl;
    return acc;
  }, {});

export const CAR_TYPE_IMAGE_BY_MAKE: Record<string, string> =
  allTypeCars.reduce<Record<string, string>>((acc, car) => {
    if (!acc[car.make]) acc[car.make] = car.imageUrl;
    return acc;
  }, {});

export const getCarTypeImageUrl = (
  make: string,
  model: string,
  fallbackImageUrl: string
): string =>
  CAR_TYPE_IMAGE_BY_MAKE_MODEL[`${make}|${model}`] ??
  CAR_TYPE_IMAGE_BY_MAKE[make] ??
  fallbackImageUrl;
